/* Le dylib distribue-t-il ses sous-interfaces directement ?
 *
 * Si CreateInterface ne rend que SteamClient, il faut passer par la table de
 * methodes d'ISteamClient, dont l'ordre n'est publie que dans le SDK
 * proprietaire. S'il rend aussi ISteamUser, ISteamApps, ISteamUtils..., on
 * atteint ces interfaces sans rien deviner. La question se tranche par la
 * mesure : on essaie les 222 chaines de version que le dylib contient
 * lui-meme.
 */
#include <windows.h>
#include <stdio.h>

typedef void *(__cdecl *fn_create)(const char *version, int *err);

static const char *versions[] = {
    "STEAMAPPLIST_INTERFACE_VERSION001",
    "STEAMAPPS_INTERFACE_VERSION001",
    "STEAMAPPS_INTERFACE_VERSION002",
    "STEAMAPPS_INTERFACE_VERSION003",
    "STEAMAPPS_INTERFACE_VERSION004",
    "STEAMAPPS_INTERFACE_VERSION005",
    "STEAMAPPS_INTERFACE_VERSION006",
    "STEAMAPPS_INTERFACE_VERSION007",
    "STEAMAPPS_INTERFACE_VERSION008",
    "STEAMAPPS_INTERFACE_VERSION009",
    "STEAMAPPTICKET_INTERFACE_VERSION001",
    "STEAMCHAT_INTERFACE_VERSION003",
    "STEAMHTTP_INTERFACE_VERSION001",
    "STEAMHTTP_INTERFACE_VERSION002",
    "STEAMHTTP_INTERFACE_VERSION003",
    "STEAMMUSICREMOTE_INTERFACE_VERSION001",
    "STEAMMUSIC_INTERFACE_VERSION001",
    "STEAMPARENTALSETTINGS_INTERFACE_VERSION001",
    "STEAMREMOTEPLAY_INTERFACE_VERSION001",
    "STEAMREMOTEPLAY_INTERFACE_VERSION002",
    "STEAMREMOTEPLAY_INTERFACE_VERSION003",
    "STEAMREMOTEPLAY_INTERFACE_VERSION004",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION001",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION002",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION003",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION004",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION005",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION006",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION007",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION008",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION009",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION010",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION011",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION012",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION013",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION014",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION015",
    "STEAMREMOTESTORAGE_INTERFACE_VERSION016",
    "STEAMSCREENSHOTS_INTERFACE_VERSION001",
    "STEAMSCREENSHOTS_INTERFACE_VERSION002",
    "STEAMSCREENSHOTS_INTERFACE_VERSION003",
    "STEAMUGC_INTERFACE_VERSION001",
    "STEAMUGC_INTERFACE_VERSION002",
    "STEAMUGC_INTERFACE_VERSION003",
    "STEAMUGC_INTERFACE_VERSION004",
    "STEAMUGC_INTERFACE_VERSION005",
    "STEAMUGC_INTERFACE_VERSION006",
    "STEAMUGC_INTERFACE_VERSION007",
    "STEAMUGC_INTERFACE_VERSION008",
    "STEAMUGC_INTERFACE_VERSION009",
    "STEAMUGC_INTERFACE_VERSION010",
    "STEAMUGC_INTERFACE_VERSION011",
    "STEAMUGC_INTERFACE_VERSION012",
    "STEAMUGC_INTERFACE_VERSION013",
    "STEAMUGC_INTERFACE_VERSION014",
    "STEAMUGC_INTERFACE_VERSION015",
    "STEAMUGC_INTERFACE_VERSION016",
    "STEAMUGC_INTERFACE_VERSION017",
    "STEAMUGC_INTERFACE_VERSION018",
    "STEAMUGC_INTERFACE_VERSION019",
    "STEAMUGC_INTERFACE_VERSION020",
    "STEAMUGC_INTERFACE_VERSION021",
    "STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001",
    "STEAMUSERSTATS_INTERFACE_VERSION001",
    "STEAMUSERSTATS_INTERFACE_VERSION002",
    "STEAMUSERSTATS_INTERFACE_VERSION003",
    "STEAMUSERSTATS_INTERFACE_VERSION004",
    "STEAMUSERSTATS_INTERFACE_VERSION005",
    "STEAMUSERSTATS_INTERFACE_VERSION006",
    "STEAMUSERSTATS_INTERFACE_VERSION007",
    "STEAMUSERSTATS_INTERFACE_VERSION008",
    "STEAMUSERSTATS_INTERFACE_VERSION009",
    "STEAMUSERSTATS_INTERFACE_VERSION010",
    "STEAMUSERSTATS_INTERFACE_VERSION011",
    "STEAMUSERSTATS_INTERFACE_VERSION012",
    "STEAMUSERSTATS_INTERFACE_VERSION013",
    "SteamAppDisableUpdate001",
    "SteamApps001",
    "SteamBilling002",
    "SteamClient006",
    "SteamClient007",
    "SteamClient008",
    "SteamClient009",
    "SteamClient010",
    "SteamClient011",
    "SteamClient012",
    "SteamClient013",
    "SteamClient014",
    "SteamClient015",
    "SteamClient016",
    "SteamClient017",
    "SteamClient018",
    "SteamClient019",
    "SteamClient020",
    "SteamClient021",
    "SteamClient022",
    "SteamClient023",
    "SteamController003",
    "SteamController004",
    "SteamController005",
    "SteamController006",
    "SteamController007",
    "SteamController008",
    "SteamFriends001",
    "SteamFriends002",
    "SteamFriends003",
    "SteamFriends004",
    "SteamFriends005",
    "SteamFriends006",
    "SteamFriends007",
    "SteamFriends008",
    "SteamFriends009",
    "SteamFriends010",
    "SteamFriends011",
    "SteamFriends012",
    "SteamFriends013",
    "SteamFriends014",
    "SteamFriends015",
    "SteamFriends016",
    "SteamFriends017",
    "SteamFriends018",
    "SteamGameCoordinator001",
    "SteamGameServer002",
    "SteamGameServer003",
    "SteamGameServer004",
    "SteamGameServer005",
    "SteamGameServer006",
    "SteamGameServer007",
    "SteamGameServer008",
    "SteamGameServer009",
    "SteamGameServer010",
    "SteamGameServer011",
    "SteamGameServer012",
    "SteamGameServer013",
    "SteamGameServer014",
    "SteamGameServer015",
    "SteamGameServerStats001",
    "SteamGameStats001",
    "SteamInput001",
    "SteamInput002",
    "SteamInput003",
    "SteamInput004",
    "SteamInput005",
    "SteamInput006",
    "SteamInput007",
    "SteamMasterServerUpdater001",
    "SteamMatchGameSearch001",
    "SteamMatchMaking001",
    "SteamMatchMaking002",
    "SteamMatchMaking003",
    "SteamMatchMaking004",
    "SteamMatchMaking005",
    "SteamMatchMaking006",
    "SteamMatchMaking007",
    "SteamMatchMaking008",
    "SteamMatchMaking009",
    "SteamMatchMakingServers001",
    "SteamMatchMakingServers002",
    "SteamMatchMakingServers003",
    "SteamNetworking001",
    "SteamNetworking002",
    "SteamNetworking003",
    "SteamNetworking004",
    "SteamNetworking005",
    "SteamNetworking006",
    "SteamNetworkingMessages002",
    "SteamNetworkingSockets002",
    "SteamNetworkingSockets003",
    "SteamNetworkingSockets004",
    "SteamNetworkingSockets005",
    "SteamNetworkingSockets006",
    "SteamNetworkingSockets008",
    "SteamNetworkingSockets009",
    "SteamNetworkingSockets010",
    "SteamNetworkingSockets011",
    "SteamNetworkingSockets012",
    "SteamNetworkingSockets013",
    "SteamNetworkingSocketsSerialized001",
    "SteamNetworkingSocketsSerialized002",
    "SteamNetworkingSocketsSerialized003",
    "SteamNetworkingSocketsSerialized004",
    "SteamNetworkingSocketsSerialized005",
    "SteamNetworkingUtils001",
    "SteamNetworkingUtils002",
    "SteamNetworkingUtils003",
    "SteamNetworkingUtils004",
    "SteamParties001",
    "SteamParties002",
    "SteamSteamVRPrivate001",
    "SteamSteamVRPrivate002",
    "SteamStreamLauncher001",
    "SteamUser004",
    "SteamUser005",
    "SteamUser006",
    "SteamUser007",
    "SteamUser008",
    "SteamUser009",
    "SteamUser010",
    "SteamUser011",
    "SteamUser012",
    "SteamUser013",
    "SteamUser014",
    "SteamUser015",
    "SteamUser016",
    "SteamUser017",
    "SteamUser018",
    "SteamUser019",
    "SteamUser020",
    "SteamUser021",
    "SteamUser022",
    "SteamUser023",
    "SteamUtils001",
    "SteamUtils002",
    "SteamUtils003",
    "SteamUtils004",
    "SteamUtils005",
    "SteamUtils006",
    "SteamUtils007",
    "SteamUtils008",
    "SteamUtils009",
    "SteamUtils010",
    "SteamUtils011",
};

int main(void)
{
    HMODULE h = LoadLibraryA("lsteamclient.dll");
    fn_create creer;
    unsigned i, ok = 0;

    if (!h) { printf("LoadLibrary a echoue : %lu\n", GetLastError()); return 1; }
    if (!(creer = (fn_create)GetProcAddress(h, "CreateInterface"))) { printf("CreateInterface absent\n"); return 1; }

    for (i = 0; i < sizeof(versions)/sizeof(versions[0]); i++) {
        int err = 0;
        void *p = creer(versions[i], &err);
        if (p) { printf("RENDU  %-45s (err %d)\n", versions[i], err); ok++; }
    }
    printf("--- %u interfaces sur %u rendues ---\n", ok, (unsigned)(sizeof(versions)/sizeof(versions[0])));
    return 0;
}
